### ISSUE TITLE
API V1 Attachment Format

### ISSUE THREAD

**Issue by eagleEggs** [SmartBear/zephyr-scale-api-v1-examples#4]
Hello!

Could you assist me with the expected format required for uploading attachments? Unfortunately I'm not seeing much online about it and I'm stuck using V1 for Zephyr Scale. The following receives error 500 and I'm sure it's not expecting the file to be in this format perhaps. Also, do you think there will be updates to V1? Thanks.

`x =  {'file': open('test.png', 'rb')}

    session = requests.Session()
    session.headers.update(
        {'Authorization': 'Bearer APIKEYHERE-REMOVED_FOR_GITHUB_POST', 'Content-Type': 'multipart/form-data'})
    response = session.post(url='{}/testrun/XX-C1/attachments'.format(endpointURL),
                            data=x,
                            verify=False)

    print(response)`

https://support.smartbear.com/zephyr-scale-server/api-docs/v1/

**Comment by eagleEggs** [comment]
This is similar to my situation but there was no response to that issue. I'm trying to upload attachment to a test in a cycle.

https://community.atlassian.com/t5/Adaptavist-questions/Can-not-upload-attachment-using-TM4J-API/qaq-p/1965909
https://community.atlassian.com/t5/Adaptavist-questions/Attaching-evidence-to-a-test-execution-API-POST/qaq-p/1239175

**Comment by nayeligarciac** [comment]
HI , 
Apologies for the delay,  I am sorry you are facing this issue. Can you create a support ticket in  [here](https://smartbear.atlassian.net/servicedesk/customer/portal/43) , so we can see this error in more detail?

Thanks, 
Nayeli

**Comment by eagleEggs** [comment]
Thanks no worries, I'll be submitting it soon - Have a good one!

**Comment by eagleEggs** [comment]
Actually I'm not even sure we have a Smart Bear Support ID lol... Is that required here?

Ok ticket is in - Thanks again.
